parameters:
  service-dir:
    default: "sdk/appcontainers"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    omit-unreachable-types: true
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/{service-name}/ContainerApps/{version-status}/{version}/openapi.json"
    emit-lro-options: "all"
    examples-dir: "{project-root}/examples"
  "@azure-tools/typespec-python":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-mgmt-appcontainers"
    namespace: "azure.mgmt.appcontainers"
    generate-test: true
    generate-sample: true
    flavor: "azure"
  "@azure-tools/typespec-java":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-resourcemanager-appcontainers"
    namespace: "com.azure.resourcemanager.appcontainers"
    service-name: "ContainerAppsApiManager"
    premium: true
    enable-sync-stack: true
    client-side-validations: true
    flavor: azure
  "@azure-tools/typespec-ts":
    emitter-output-dir: "{output-dir}/{service-dir}/arm-appcontainers"
    compatibility-lro: true
    flavor: "azure"
    experimental-extensible-enums: true
    package-details:
      name: "@azure/arm-appcontainers"
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/appcontainers"
    emitter-output-dir: "{output-dir}/{service-dir}/arm-appcontainers"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/arm-appcontainers"
    fix-const-stuttering: true
    flavor: "azure"
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
